### ISSUE TITLE
shift-a (append to end of line) isn't correct

### ISSUE THREAD

**Issue by Torrencem** [nielstron/vimulator#10]
When I hit shift-a in vim, I expect to then be in insert mode at the end of the line. In the plugin however, shift-a brings me _before_ the final character in the line. For example, the following sequences of inputs give different text in the plugin and in vim:

```
<i> alphabet <esc> <h> <h>  <shift+a> !
```
In vim, this produces the string "alphabet!", but in the plugin, this writes "alphabe!t"

**Comment by nielstron** [comment]
I could not reproduce this with `master`. Which version of the Plugin are you using?

**Comment by nielstron** [comment]
Thanks for pointing this out. It was actually already fixed in `dev` but did not find its way to `master` yet. I will release a new version with the fix now.

**Comment by Torrencem** [comment]
Awesome, I appreciate it!
