### ISSUE TITLE
jedit says vimulator requires java 15; I installed openjdk 17 but it's not finding it

### ISSUE THREAD

**Issue by TimFH** [nielstron/vimulator#12]
Running Ubuntu 18.04.1 and jedit 5.5.0
In response to jedit's complaint I installed openjdk-17-jre, and when I type "java --version" it finds it, but when I open jedit it still says I have java 11 not 15 or up.
How can I tell jedit I have 17? I would uninstall openjdk-11-jre but I think the rest of jedit still depends on it!

**Comment by nielstron** [comment]
I don't think this question is related to vimulator. I also dont know how to help you with it. Please consider opening an issue at the jedit repository.
